-- Disable Row-Level Security on all tables for development
ALTER TABLE ausencias DISABLE ROW LEVEL SECURITY;
ALTER TABLE semanas DISABLE ROW LEVEL SECURITY;
ALTER TABLE tracking DISABLE ROW LEVEL SECURITY;
ALTER TABLE rutinas DISABLE ROW LEVEL SECURITY;
ALTER TABLE sesiones DISABLE ROW LEVEL SECURITY;
ALTER TABLE ejercicios DISABLE ROW LEVEL SECURITY;
